services:
  - type: web
    name: slack-ml-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: SLACK_BOT_TOKEN
        sync: false
      - key: SLACK_CHANNEL
        sync: false
      - key: PORT
        value: 10000